// <auto-generated />
using System;
using LeadsProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeadsProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615104937_AddPhoneCalls")]
    partial class AddPhoneCalls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeadsProject.Models.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AirDirections")
                        .HasColumnType("int");

                    b.Property<string>("Amenities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("int");

                    b.Property<string>("Budget")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Financing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Floor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Intent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NearBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneCalls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rooms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timeline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transcript")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.ToTable("Leads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = "תל אביב - פלורנטין",
                            AssignedToId = 2,
                            Budget = "2,500,000",
                            ContactName = "דוד לוי",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Financing = "הון עצמי + משכנתא",
                            Floor = "3",
                            Intent = "קניה",
                            Notes = "לקוח רציני מאוד, יש לו אישור עקרוני מהבנק. לחזור אליו עד יום ג'",
                            Phone = "054-7654321",
                            PropertyType = "דירה",
                            Rating = "hot",
                            Rooms = "4",
                            Status = "assigned",
                            Timeline = "3 חודשים",
                            Transcript = "[\n  {\"speaker\":\"agent\",\"text\":\"שלום, אני מאריה כהן גרופ, איך אוכל לעזור?\"},\n  {\"speaker\":\"client\",\"text\":\"שלום, ראיתי מודעה על דירת 4 חדרים בתל אביב\"},\n  {\"speaker\":\"agent\",\"text\":\"כן בטח, באיזה אזור בתל אביב אתה מחפש?\"},\n  {\"speaker\":\"client\",\"text\":\"רצוי פלורנטין או לב תל אביב\"},\n  {\"speaker\":\"agent\",\"text\":\"מה התקציב שלך?\"},\n  {\"speaker\":\"client\",\"text\":\"בערך שניים וחצי מיליון, יש לי הון עצמי של 800 אלף\"},\n  {\"speaker\":\"agent\",\"text\":\"ומתי אתה מתכנן לקנות?\"},\n  {\"speaker\":\"client\",\"text\":\"תוך 3 חודשים, אני כבר רציני בעניין\"},\n  {\"speaker\":\"agent\",\"text\":\"מעולה, אשלח לך כמה נכסים רלוונטיים. מה הטלפון שלך?\"},\n  {\"speaker\":\"client\",\"text\":\"054-7654321\"}\n]",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Area = "השרון - נתניה / חדרה",
                            AssignedToId = 3,
                            Budget = "1,500,000",
                            ContactName = "יעקב לוי",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Financing = "הון עצמי",
                            Floor = "2",
                            Intent = "השקעה",
                            Notes = "מחפש תשואה מעל 4%, פנוי לפגישה בסוף שבוע",
                            Phone = "052-1112233",
                            PropertyType = "דירה",
                            Rating = "warm",
                            Rooms = "3",
                            Status = "assigned",
                            Timeline = "גמיש",
                            Transcript = "[\n  {\"speaker\":\"agent\",\"text\":\"בוקר טוב, כאן משרד אורן כהן גרופ\"},\n  {\"speaker\":\"client\",\"text\":\"בוקר טוב, חיפשתי דירה להשקעה באזור השרון\"},\n  {\"speaker\":\"agent\",\"text\":\"בשמחה, מה התקציב שעומד לרשותך?\"},\n  {\"speaker\":\"client\",\"text\":\"עד מיליון וחצי, להשכרה אחר כך\"},\n  {\"speaker\":\"agent\",\"text\":\"כמה חדרים אתה מחפש?\"},\n  {\"speaker\":\"client\",\"text\":\"3 חדרים מספיק, הכי חשוב לי תשואה טובה\"},\n  {\"speaker\":\"agent\",\"text\":\"יש לנו כמה נכסים מעניינים בנתניה וחדרה. תרצה שנקבע פגישה?\"},\n  {\"speaker\":\"client\",\"text\":\"כן בהחלט, אני פנוי בסוף השבוע\"},\n  {\"speaker\":\"agent\",\"text\":\"מצוין, מה שמך?\"},\n  {\"speaker\":\"client\",\"text\":\"יעקב לוי, 052-1112233\"}\n]",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Area = "ירושלים - בקעה / רחביה",
                            Budget = "7,000 לחודש",
                            ContactName = "שרה כץ",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Intent = "שכירות",
                            Notes = "זוג + ילד, צריכים לעבור בעוד חודשיים",
                            Phone = "050-9876543",
                            PropertyType = "דירה",
                            Rating = "warm",
                            Rooms = "3",
                            Status = "new",
                            Timeline = "חודשיים",
                            Transcript = "[\n  {\"speaker\":\"agent\",\"text\":\"שלום, במה אוכל לסייע?\"},\n  {\"speaker\":\"client\",\"text\":\"שלום, אני מחפשת דירת שכירות לזוג בירושלים\"},\n  {\"speaker\":\"agent\",\"text\":\"באיזה אזור בירושלים?\"},\n  {\"speaker\":\"client\",\"text\":\"קרמי עדה, בקעה, או רחביה\"},\n  {\"speaker\":\"agent\",\"text\":\"מה התקציב לשכירות לחודש?\"},\n  {\"speaker\":\"client\",\"text\":\"עד 7,000 שקל בחודש\"},\n  {\"speaker\":\"agent\",\"text\":\"כמה חדרים?\"},\n  {\"speaker\":\"client\",\"text\":\"3 חדרים, אנחנו זוג ועוד ילד אחד\"},\n  {\"speaker\":\"agent\",\"text\":\"מתי אתם צריכים להיכנס?\"},\n  {\"speaker\":\"client\",\"text\":\"בעוד חודשיים, הסכם קיים נגמר\"},\n  {\"speaker\":\"agent\",\"text\":\"בסדר גמור, נשלח לך אפשרויות. מה הטלפון?\"},\n  {\"speaker\":\"client\",\"text\":\"050-9876543, שרה כץ\"}\n]",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Area = "הרצליה פיתוח",
                            Budget = "3,200,000",
                            ContactName = "משה אברהם",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Financing = "הון עצמי",
                            Floor = "8",
                            Intent = "קניה",
                            Notes = "עדיין בשלב בדיקה, לא בטוח בתקציב",
                            Phone = "053-4445566",
                            PropertyType = "פנטהאוז",
                            Rating = "cold",
                            Rooms = "5",
                            Status = "new",
                            Timeline = "6 חודשים",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Area = "ראשון לציון",
                            AssignedToId = 4,
                            Budget = "1,800,000",
                            ContactName = "רחל גולן",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Financing = "משכנתא",
                            Floor = "1",
                            Intent = "קניה",
                            Notes = "דחוף! פגישה נקבעה ליום חמישי. מחפשת קרקע קרובה לבית ספר",
                            Phone = "058-7778899",
                            PropertyType = "דירה",
                            Rating = "hot",
                            Rooms = "4",
                            Status = "assigned",
                            Timeline = "מיידי",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LeadsProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "מנהל",
                            PasswordHash = "$2a$11$dbmf3NkHS1vlCeQsItm/N.vH0/V/3djqlaTlY8Ju/2m6dWT6W8QCu",
                            Role = "manager"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "אריה",
                            PasswordHash = "$2a$11$uNZfTiZUOcvitu0XVrwV3OrrE/NHXQAKyaZNrBwjbF5XCBlP5pkDu",
                            Role = "agent"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "דב",
                            PasswordHash = "$2a$11$rQlA.QIpOLIyq4V9KNPV0.GGV.AhlLcJ7AJR98ws65Axfpm7vgtF2",
                            Role = "agent"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "רבקה",
                            PasswordHash = "$2a$11$inJ3SalgBlZlCbfSvQdlVeWDkFuVNa..RUau3iRkaNiHGZrY3l6bu",
                            Role = "agent"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "מוישי",
                            PasswordHash = "$2a$11$DHln4/xpzT.frwOBpj9Cmey2Cl2n0HOTBsbcNeu3hSf07fJhFGsre",
                            Role = "agent"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "מיכאל",
                            PasswordHash = "$2a$11$zwWqrHSExHrLVynIKASTeuCAfUV1v6FCdEjtXtw4NjGLHnq/rtXM6",
                            Role = "agent"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "אהרון",
                            PasswordHash = "$2a$11$p3l0YLvuCMhRy2bz1qhT0OumFpniQQH/gGIAMXwdqB7rf2vDvwGqO",
                            Role = "agent"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "ליסה",
                            PasswordHash = "$2a$11$K6hgNYxIbsuNXr8teZdzUuNh5lbogkxR8lUmrqqQPDHJ7B3UH7Gby",
                            Role = "agent"
                        });
                });

            modelBuilder.Entity("LeadsProject.Models.Lead", b =>
                {
                    b.HasOne("LeadsProject.Models.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId");

                    b.Navigation("AssignedTo");
                });
#pragma warning restore 612, 618
        }
    }
}
